[package]
name = "stucco-ast"
version = "0.1.0"
edition = "2021"

[features]
print = ["syn/extra-traits"]
span-locations = ["proc-macro2/span-locations"]
default = ["print"]

[dependencies]
common = { workspace = true }
syn = { workspace = true }
proc-macro2 = { workspace = true }
