[package]
name = "stucco_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.86"
stucco_derive_impl = { version = "0.1.0", path = "../derive_impl" }
