[package]
name = "stucco_runner"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.86"
syn = {version = "2.0.71", features = ["extra-traits","full"]}
quote = "1.0.36"
parser = { workspace = true }
ast = { workspace = true }
compiler = { workspace = true }

